### ISSUE TITLE
No data is comming out may i know the reson why ?

### ISSUE THREAD

**Issue by badharan** [ipHeaders/silverpeak-prometheus#21] opened 2023-02-27 20:58 UTC
# HELP activeAlarms summary of active alarms for Orchestrator and all appliances
# TYPE activeAlarms gauge

**Comment by badharan** [comment] 2023-02-27 21:00
config:
   exporter:
      port: 15693
   silverpeak:
      orch: xxxxxxxxx
      verify_ssl: False

orchestrator:
   collect: True
   interval: 300

appliances:
   EDGE-1:
      - {system: true, interval: 120}
      - {bgp: true, interval: 120}
    EDGE -2:
      - {system: true, interval: 120}
      - {bgp: true, interval: 120}

**Comment by badharan** [comment] 2023-02-27 21:01
the above is my cofig , 
my question is how can we find the name of the edge in the orch UI ? if is that correct will i get the data out

**Comment by ipHeaders** [comment] 2023-02-27 22:52
When you login into the Orchestrator on the left side you will have a tab with all your appliances. What ever name it has there is the name you need to put on the yml file. Does that makes sense?

**Comment by badharan** [comment] 2023-02-28 11:34
2Appliances 
	site 1 - Chennai
             hostname(ip_add)
        site 2 - singapore
             hostname(IP)

we need to use the  site name or hostname ?

**Comment by ipHeaders** [comment] 2023-02-28 14:58
you need to use the hostname

**Comment by ipHeaders** [comment] 2023-03-01 14:49
Please let me know if you got it working so i can close this out.

**Comment by badharan** [comment] 2023-03-01 18:44
![image](https://user-images.githubusercontent.com/108415952/222235112-df300de6-2227-4969-b41b-53382841515b.png)


After 7 sec the container restarts ? why ?

**Comment by badharan** [comment] 2023-03-01 19:19
![image](https://user-images.githubusercontent.com/108415952/222242214-1b7ad757-02aa-410a-877e-aeb9d6dcb465.png)


Bgb alone comes with no data , in the vars.yml i checked its true .

**Comment by ipHeaders** [comment] 2023-03-01 20:42
How are you running the tool? 
Docker or Python Library via Pypi.

The next step would be to run the tool in debug mode to see what the issue is. Maybe the API key being used doesn't have permission to see the resources in the orchestrator.

If you have discord you can contact me here - lazg#9531

**Comment by ipHeaders** [comment] 2023-03-07 04:32
any update here? or we can close this out?

**Comment by ipHeaders** [comment] 2023-03-16 00:48
closing issue

**Closed by ipHeaders** 2023-03-16 00:48 UTC
Labels: bug
